# Generated by Django 2.2.28 on 2024-03-01 20:06

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import wad.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
                ('cuisine', models.CharField(choices=[('italian', 'Italian'), ('chinese', 'Chinese'), ('thai', 'Thai'), ('indian', 'Indian')], max_length=7)),
                ('ingredients', models.TextField(max_length=1024)),
                ('instructions', models.TextField(max_length=1024)),
                ('avgStarRating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('image', models.ImageField(upload_to=wad.models.user_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('forename', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('dateOfBirth', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('website', models.URLField(blank=True)),
                ('picture', models.ImageField(blank=True, upload_to='profile_images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='starRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(limit_value=5), django.core.validators.MinValueValidator(limit_value=0)])),
                ('recipeID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wad.Recipe')),
                ('userID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wad.UserProfile')),
            ],
        ),
    ]
