# Generated by Django 2.2.28 on 2024-03-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0005_auto_20240308_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
