# Generated by Django 2.2.28 on 2024-03-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0007_auto_20240312_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(default=None),
        ),
    ]
