# Generated by Django 2.2.28 on 2024-03-15 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [('wad', '0009_auto_20240315_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
