# Generated by Django 2.2.28 on 2024-03-19 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0012_auto_20240315_1320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='starrating',
            old_name='recipeID',
            new_name='recipe_id',
        ),
    ]
