# Generated by Django 2.2.28 on 2024-03-20 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0014_auto_20240319_1319'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='starrating',
            unique_together={('userID', 'recipeID')},
        ),
    ]
