# Generated by Django 2.2.28 on 2024-03-21 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wad', '0015_auto_20240320_1022'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='starrating',
            unique_together=set(),
        ),
    ]
